// https://gist.github.com/incredimike/1469814
// By: incredimike

export default countryList = [
	"Argentina",
	"Australia",
	"Afghanistan",
    "Algeria",
    "Angola",
    "Bolivia",
    "Albania",
    "Austria",
    "Belgium",
    "Brazil",
    "Chile",
    "China",
    "Cameroon",
	"Canada",
    "Colombia",
    "Costa Rica",
	"Croatia",
    "Cuba",
    "Congo",
    "Bulgaria",
    "Denmark",
	"Ecuador",
	"England",
    "Egypt",
    "France",
	"Germany",
	"Ghana",
	"Greece",
    "Honduras",
	"Iceland",
    "India",
    "Italy",
    "Korea",
    "Japan",
    "United States",
    "Uruguay",
    "Mexico",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Panama",
    "Paraguay",
    "Peru",
    "Poland",
    "Portugal",
    "Senegal",
    "Romania",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Finland",
    
	"American Samoa",
	"Andorra",
	"Anguilla",
	"Antarctica",
	"Armenia",
	"Aruba",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"British Indian Ocean Territory",
	"Brunei Darussalam",
	"Burkina Faso",
	"Burundi",
	"Cabo Verde",
	"Cambodia",
	"Cayman Islands",
	"Central African Republic",
	"Chad",
	"Christmas Island",
	"Cocos (Keeling) Islands",
	"Comoros",
	"Cook Islands",
	"Curaçao",
	"Cyprus",
	"Czechia",
	"Côte d'Ivoire",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Eswatini",
	"Ethiopia",
	"Falkland Islands",
	"Faroe Islands",
	"Fiji",
	"Gabon",
	"Gambia",
	"Georgia",
	"Gibraltar",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See",
	"Hong Kong",
	"Hungary",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Jamaica",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Kuwait",
	"Kyrgyzstan",
	"Lao People's Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Martinique",
	"Mauritania",
	"Mauritius",
    "Mayotte",
    "Micronesia (Federated States of)",
	"Moldova (the Republic of)",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
    "Nepal",
	"New Caledonia",
    "Nicaragua",
	"Niger",
    "Niue",
	"Norfolk Island",
	"Northern Mariana Islands",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestine, State of",
    "Papua New Guinea",
    "Philippines",
	"Pitcairn",
    "Puerto Rico",
	"Qatar",
	"Republic of North Macedonia",
	"Russian Federation",
	"Rwanda",
	"Réunion",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Seychelles",
	"Sierra Leone",
	"Singapore",
    "Sint Maarten (Dutch part)",
	"Solomon Islands",
	"Somalia",
    "South Georgia and the South Sandwich Islands",
    "South Sudan",
    "Sri Lanka",
	"Sudan",
	"Suriname",
	"Svalbard and Jan Mayen",
    "Syrian Arab Republic",
	"Taiwan (Province of China)",
	"Tajikistan",
	"Tanzania, United Republic of",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
    "Turkmenistan",
	"Turks and Caicos Islands",
	"Tuvalu",
	"Uganda",
	"Ukraine",
	"United Arab Emirates",
	"United Kingdom of Great Britain and Northern Ireland",
    "Uzbekistan",
	"Vanuatu",
	"Venezuela",
	"Viet Nam",
	"Virgin Islands",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands"
];